apiVersion: apps/v1
kind: Deployment
metadata:
  name: xdp-drop
  labels:
    k8s-app: xdp-drop
spec:
  selector:
    matchLabels:
      name: xdp-drop
  replicas: 0
  template:
    metadata:
      labels:
        name: xdp-drop
    spec:
      serviceAccountName: default
      hostNetwork: true
      containers:
      - name: xdp-drop
        image: ghcr.io/hemslo/sre-games-2023:sha-aa1e0ee
        securityContext:
          privileged: true
        env:
        - name: DEVICE
          value: br-ex
        - name: SLEEP_TIME
          value: "600"
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-src
          mountPath: /usr/src
        - name: kernel-debug
          mountPath: /sys/kernel/debug
      terminationGracePeriodSeconds: 10
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
